# Generated by Django 6.0.5 on 2026-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="iso_type",
            field=models.CharField(
                choices=[("ISO 27001", "Iso 27001"), ("ISO 27002", "Iso 27002")],
                default="ISO 27001",
                max_length=20,
            ),
        ),
    ]
