from audits.models import Control
from django.core.management.base import BaseCommand


class Command(BaseCommand):

	help = "Popula os controles do ISO 27001"

	def handle(self, *args, **kwargs):
		controls = [
			{
				"code": "5.1",
				"title": "Políticas de segurança da informação",
				"description": "A política de segurança da informação e as políticas específicas por tema devem ser definidas, aprovadas pela direção, publicadas, comunicadas e reconhecidas pelo pessoal pertinente e pelas partes interessadas pertinentes, e analisadas criticamente em intervalos planejados e quando ocorrerem mudanças significativas.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.2",
				"title": "Papéis e responsabilidades pela segurança da informação",
				"description": "Papéis e responsabilidades pela segurança da informação devem ser definidos e alocados de acordo com as necessidades da organização.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.3",
				"title": "Segregação de funções",
				"description": "Funções conflitantes e áreas de responsabilidade conflitantes devem ser segregadas.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.4",
				"title": "Responsabilidades da direção",
				"description": "A direção deve requerer que todo o pessoal aplique a segurança da informação de acordo com a política da segurança da informação estabelecida, com as políticas específicas por tema e com os procedimentos da organização.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.5",
				"title": "Contato com autoridades",
				"description": "A organização deve estabelecer e manter contato com as autoridades relevantes.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.6",
				"title": "Contato com grupos de interesse especial",
				"description": "A organização deve estabelecer e manter contato com grupos de interesse especial ou com outros fóruns de especialistas em segurança e associações profissionais.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.7",
				"title": "Inteligência de ameaças",
				"description": "As informações relacionadas a ameaças à segurança da informação devem ser coletadas e analisadas para produzir inteligência de ameaças.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.8",
				"title": "Segurança da informação no gerenciamento de projetos",
				"description": "A segurança da informação deve ser integrada ao gerenciamento de projetos.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.9",
				"title": "Inventário de informações e outros ativos associados",
				"description": "Um inventário de informações e outros ativos associados, incluindo proprietários, deve ser desenvolvido e mantido.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.10",
				"title": "Uso aceitável de informações e outros ativos associados",
				"description": "Regras para o uso aceitável e procedimentos para o manuseio de informações e outros ativos associados devem ser identificados, documentados e implementados.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.11",
				"title": "Devolução de ativos",
				"description": "O pessoal e outras partes interessadas, conforme apropriado, devem devolver todos os ativos da organização em sua posse em mudança ou o encerramento de seu emprego, contratação ou acordo.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.12",
				"title": "Classificação das informações",
				"description": "As informações devem ser classificadas de acordo com as necessidades de segurança da informação da organização, com base na confidencialidade, integridade, disponibilidade e requisitos das partes interessadas relevantes.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.13",
				"title": "Rotulagem de informações",
				"description": "Um conjunto adequado de procedimentos para rotulagem de informações deve ser desenvolvido e implementado de acordo com o esquema de classificação de informações adotado pela organização.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.14",
				"title": "Transferência de informações",
				"description": "Regras, procedimentos ou acordos de transferência de informações devem ser implementados para todos os tipos de recursos de transferência dentro da organização e entre a organização e outras partes.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.15",
				"title": "Controle de acesso",
				"description": "Regras para controlar o acesso físico e lógico às informações e a outros ativos associados devem ser estabelecidas e implementadas com base nos requisitos de segurança da informação e de negócios.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.16",
				"title": "Gestão de identidade",
				"description": "O ciclo de vida completo das identidades deve ser gerenciado.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.17",
				"title": "Informações de autenticação",
				"description": "A alocação e a gestão de informações de autenticação devem ser controladas por um processo de gestão, incluindo aconselhar o pessoal sobre o manuseio adequado de informações de autenticação.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.18",
				"title": "Direitos de acesso",
				"description": "Os direitos de acesso às informações e a outros ativos associados devem ser provisionados, analisados criticamente, modificados e removidos de acordo com a política específica por tema e com as regras da organização para o controle de acesso.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.19",
				"title": "Segurança da informação nas relações com fornecedores",
				"description": "Processos e procedimentos devem ser definidos e implementados para gerenciar os riscos da segurança da informação associados com o uso dos produtos ou serviços dos fornecedores.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.20",
				"title": "Abordagem da segurança da informação nos contratos de fornecedores",
				"description": "Requisitos relevantes de segurança da informação devem ser estabelecidos e acordados com cada fornecedor, com base no tipo de relacionamento com o fornecedor.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.21",
				"title": "Gestão da segurança da informação na cadeia de fornecimento de tecnologia de informação e comunicação (TIC)",
				"description": "Processos e procedimentos devem ser definidos e implementados para gerenciar os riscos da segurança da informação associados à cadeia de fornecimento de produtos e serviços de TIC.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.22",
				"title": "Monitoramento, análise crítica e gestão de mudanças dos serviços de fornecedores",
				"description": "A organização deve monitorar, analisar criticamente, avaliar e gerenciar regularmente a mudança nas práticas da segurança da informação dos fornecedores e na prestação de serviços.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.23",
				"title": "Segurança da informação para uso de serviços em nuvem",
				"description": "Os processos de aquisição, uso, gestão e saída de serviços em nuvem devem ser estabelecidos de acordo com os requisitos da segurança da informação da organização.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.24",
				"title": "Planejamento e preparação da gestão de incidentes da segurança da informação",
				"description": "A organização deve planejar e se preparar para gerenciar incidentes da segurança da informação, definindo, estabelecendo e comunicando processos, papéis e responsabilidades de gestão de incidentes da segurança da informação.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.25",
				"title": "Avaliação e decisão sobre eventos da segurança da informação",
				"description": "A organização deve avaliar os eventos da segurança da informação e decidir se categoriza como incidentes da segurança da informação.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.26",
				"title": "Resposta a incidentes da segurança da informação",
				"description": "Os incidentes da segurança da informação devem ser respondidos de acordo com os procedimentos documentados.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.27",
				"title": "Aprendizado com incidentes de segurança da informação",
				"description": "O conhecimento adquirido com incidentes de segurança da informação deve ser usado para fortalecer e melhorar os controles da segurança da informação.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.28",
				"title": "Coleta de evidências",
				"description": "A organização deve estabelecer e implementar procedimentos para identificação, coleta, aquisição e preservação de evidências relacionadas a eventos da segurança da informação.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.29",
				"title": "Segurança da informação durante a disrupção",
				"description": "A organização deve planejar como manter a segurança da informação em um nível apropriado durante a disrupção.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.30",
				"title": "Prontidão de TIC para continuidade de negócios",
				"description": "A prontidão de TIC deve ser planejada, implementada, mantida e testada com base nos objetivos de continuidade de negócios e nos requisitos de continuidade da TIC.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.31",
				"title": "Requisitos legais, estatutários, regulamentares e contratuais",
				"description": "Os requisitos legais, estatutários, regulamentares e contratuais pertinentes à segurança da informação e a abordagem da organização para atender a esses requisitos devem ser identificados, documentados e atualizados.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.32",
				"title": "Direitos de propriedade intelectual",
				"description": "A organização deve implementar procedimentos adequados para proteger os direitos de propriedade intelectual.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.33",
				"title": "Proteção de registros",
				"description": "Os registros devem ser protegidos contra perdas, destruição, falsificação, acesso não autorizado e liberação não autorizada.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.34",
				"title": "Privacidade e proteção de DP",
				"description": "A organização deve identificar e atender aos requisitos relativos à preservação da privacidade e à proteção de DP, de acordo com as leis e os regulamentos aplicáveis e requisitos contratuais.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.35",
				"title": "Análise crítica independente da segurança da informação",
				"description": "A abordagem da organização para gerenciar a segurança da informação e sua implementação, incluindo pessoas, processos e tecnologias, devem ser analisadas criticamente, de forma independente a intervals planejados ou quando ocorrerem mudanças significativas.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.36",
				"title": "Compliance com políticas, regras e normas para segurança da informação",
				"description": "O compliance com a política de segurança da informação da organização, políticas específicas por tema, regras e normas deve ser analisado criticamente a intervalos regulares.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "5.37",
				"title": "Documentação dos procedimentos de operação",
				"description": "Os procedimentos de operação dos recursos de processamento das informações devem ser documentados e disponibilizados para o pessoal que necessite deles.",
				"type": "controles organizacionais",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.1",
				"title": "Seleção",
				"description": "Verificações de antecedentes de todos os candidatos a serem contratados devem ser realizadas antes de ingressarem na organização e de modo contínuo, de acordo com as leis, os regulamentos e a ética aplicáveis, e devem ser proporcionais aos requisitos do negócio, à classificação das informações a serem acessadas e aos riscos percebidos.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.2",
				"title": "Termos e condições de contratação",
				"description": "Os contratos trabalhistas devem declarar as responsabilidades do pessoal e da organização para a segurança da informação.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.3",
				"title": "Conscientização, educação e treinamento em segurança da informação",
				"description": "O pessoal da organização e partes interessadas relevantes devem receber treinamento, educação e conscientização em segurança da informação apropriados e atualizações regulares da política de segurança da informação da organização, políticas específicas por tema e procedimentos, conforme pertinente para as suas funções.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.4",
				"title": "Processo disciplinar",
				"description": "Um processo disciplinar deve ser formalizado e comunicado, para tomar ações contra pessoal e outras partes interessadas relevantes que tenham cometido uma violação da política da segurança da informação.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.5",
				"title": "Responsabilidades após encerramento ou mudança da contratação",
				"description": "As responsabilidades e funções de segurança da informação que permaneçam válidas após o encerramento ou a mudança da contratação devem ser definidas, aplicadas e comunicadas ao pessoal e a outras partes interessadas pertinentes.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.6",
				"title": "Acordos de confidencialidade ou não divulgação",
				"description": "Acordos de confidencialidade ou não divulgação que reflitam as necessidades da organização para a proteção das informações devem ser identificados, documentados, analisados criticamente em intervalos regulares e assinados pelo pessoal e por outras partes interessadas pertinentes.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.7",
				"title": "Trabalho remoto",
				"description": "Medidas de segurança devem ser implementadas quando as pessoas estiverem trabalhando remotamente para proteger as informações acessadas, tratadas ou armazenadas fora das instalações da organização.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "6.8",
				"title": "Relato de eventos de segurança da informação",
				"description": "A organização deve fornecer um mecanismo para que as pessoas relatem eventos da segurança da informação observados ou suspeitos por meio de canais apropriados em tempo hábil.",
				"type": "controles de pessoas",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.1",
				"title": "Perímetros de segurança física",
				"description": "Perímetros de segurança devem ser definidos e usados para proteger áreas que contenham informações e outros ativos associados.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.2",
				"title": "Entrada física",
				"description": "As áreas seguras devem ser protegidas por controles de entrada e pontos de acesso apropriados.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.3",
				"title": "Segurança de escritórios, salas e instalações",
				"description": "Segurança física para escritórios, salas e instalações deve ser projetada e implementada.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.4",
				"title": "Monitoramento de segurança física",
				"description": "As instalações devem ser monitoradas continuamente quanto a acesso físico não autorizado.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.5",
				"title": "Proteção contra ameaças físicas e ambientais",
				"description": "Proteção contra ameaças físicas e ambientais, como desastres naturais e outras ameaças físicas intencionais ou não intencionais à infraestrutura, deve ser projetada e implementada.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.6",
				"title": "Trabalho em áreas seguras",
				"description": "Medidas de segurança para trabalhar em áreas seguras devem ser projetadas e implementadas.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.7",
				"title": "Mesa limpa e tela limpa",
				"description": "Regras de mesa limpa para documentos impressos e mídia de armazenamento removível e regras de tela limpa para os recursos de processamento de informações devem ser definidas e adequadamente aplicadas.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.8",
				"title": "Localização e proteção de equipamentos",
				"description": "Os equipamentos devem ser posicionados com segurança e proteção.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.9",
				"title": "Segurança de ativos fora das instalações da organização",
				"description": "Os ativos fora das instalações da organização devem ser protegidos.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.10",
				"title": "Mídia de armazenamento",
				"description": "As mídias de armazenamento devem ser gerenciadas por seu ciclo de vida de aquisição, uso, transporte e descarte, de acordo com o esquema de classificação e com os requisitos de manuseio da organização.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.11",
				"title": "Serviços de infraestrutura",
				"description": "As instalações de processamento de informações devem ser protegidas contra falhas de energia e outras disrupções causadas por falhas nos serviços de infraestrutura.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.12",
				"title": "Segurança do cabeamento",
				"description": "Os cabos que transportam energia ou dados, ou que sustentam serviços de informação, devem ser protegidos contra interceptação, interferência ou danos.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.13",
				"title": "Manutenção de equipamentos",
				"description": "Os equipamentos devem ser mantidos corretamente para assegurar a disponibilidade, integridade e confidencialidade da informação.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "7.14",
				"title": "Descarte seguro ou reutilização de equipamentos",
				"description": "Os itens dos equipamentos que contenham mídia de armazenamento devem ser verificados para assegurar que quaisquer dados sensíveis e software licenciado tenham sido removidos ou sobrescritos com segurança antes do descarte ou reutilização.",
				"type": "controles físicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.1",
				"title": "Dispositivos endpoint do usuário",
				"description": "Informações armazenadas, processadas ou acessíveis por meio de dispositivos endpoint do usuário devem ser protegidas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.2",
				"title": "Direitos de acessos privilegiados",
				"description": "A atribuição e o uso de direitos de acessos privilegiados devem ser restritos e gerenciados.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.3",
				"title": "Restrição de acesso à informação",
				"description": "O acesso às informações e a outros ativos associados deve ser restrito de acordo com a política específica por tema sobre controle de acesso.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.4",
				"title": "Acesso ao código-fonte",
				"description": "Os acessos de leitura e escrita ao código-fonte, ferramentas de desenvolvimento e bibliotecas de software devem ser adequadamente gerenciados.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.5",
				"title": "Autenticação segura",
				"description": "Tecnologia e procedimentos de autenticação segura devem ser implementados, com base em restrições de acesso à informação e à política específica por tema de controle de acesso.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.6",
				"title": "Gestão de capacidade",
				"description": "O uso dos recursos deve ser monitorado e ajustado de acordo com os requisitos de capacidade atual e esperada.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.7",
				"title": "Proteção contra malware",
				"description": "Proteção contra malware deve ser implementada e apoiada pela conscientização adequada do usuário.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.8",
				"title": "Gestão de vulnerabilidades técnicas",
				"description": "Informações sobre vulnerabilidades técnicas dos sistemas de informação em uso devem ser obtidas; a exposição da organização a tais vulnerabilidades deve ser avaliada e medidas apropriadas devem ser tomadas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.9",
				"title": "Gestão de configuração",
				"description": "As configurações, incluindo configurações de segurança, de hardware, software, serviços e redes, devem ser estabelecidas, documentadas, implementadas, monitoradas e analisadas criticamente.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.10",
				"title": "Exclusão de informações",
				"description": "As informações armazenadas em sistemas de informação, dispositivos ou em qualquer outra mídia de armazenamento devem ser excluídas quando não forem mais necessárias.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.11",
				"title": "Mascaramento de dados",
				"description": "O mascaramento de dados deve ser usado de acordo com a política específica por tema da organização sobre o controle de acesso e outras políticas específicas por tema relacionadas e requisitos do negócio, levando em consideração a legislação aplicável.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.12",
				"title": "Prevenção de vazamento de dados",
				"description": "As medidas de prevenção de vazamento de dados devem ser aplicadas a sistemas, redes e quaisquer outros dispositivos que processem, armazenem ou transmitam informações sensíveis.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.13",
				"title": "Backup das informações",
				"description": "Cópias de backup de informações, software e sistemas devem ser mantidas e testadas regularmente de acordo com a política específica por tema acordada sobre backup.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.14",
				"title": "Redundância dos recursos de processamento de informações",
				"description": "Recursos de processamento de informações devem ser implementados com redundância suficiente para atender aos requisitos de disponibilidade.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.15",
				"title": "Log",
				"description": "Logs que registrem atividades, exceções, falhas e outros eventos relevantes devem ser produzidos, armazenados, protegidos e analisados.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.16",
				"title": "Atividades de monitoramento",
				"description": "As redes, sistemas e aplicações devem ser monitoradas quanto a comportamentos anômalos e ações apropriadas devem ser tomadas para avaliar possíveis incidentes de segurança da informação.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.17",
				"title": "Sincronização do relógio",
				"description": "Os relógios dos sistemas de processamento de informações utilizados pela organização devem ser sincronizados com fontes de tempo aprovadas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.18",
				"title": "Uso de programas utilitários privilegiados",
				"description": "O uso de programas utilitários que possam ser capazes de se sobrepor a controles de sistema e de aplicações deve ser restrito e rigorosamente controlado.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.19",
				"title": "Instalação de software em sistemas operacionais",
				"description": "Procedimentos e medidas devem ser implementados para gerenciar com segurança a instalação de software em sistemas operacionais.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.20",
				"title": "Segurança de redes",
				"description": "Redes e dispositivos de rede devem ser protegidos, gerenciados e controlados para proteger as informações em sistemas e aplicações.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.21",
				"title": "Segurança dos serviços de rede",
				"description": "Mecanismos de segurança, níveis de serviço e requisitos de serviços de rede devem ser identificados, implementados e monitorados.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.22",
				"title": "Segregação de redes",
				"description": "Grupos de serviços de informação, usuários e sistemas de informação devem ser segregados nas redes da organização.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.23",
				"title": "Filtragem da web",
				"description": "O acesso a websites externos deve ser gerenciado para reduzir a exposição a conteúdo malicioso.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.24",
				"title": "Uso de criptografia",
				"description": "Regras para o uso efetivo da criptografia, incluindo o gerenciamento de chaves criptográficas devem ser definidas e implementadas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.25",
				"title": "Ciclo de vida de desenvolvimento seguro",
				"description": "Regras para o desenvolvimento seguro de software e sistemas devem ser estabelecidas e aplicadas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.26",
				"title": "Requisitos de segurança da aplicação",
				"description": "Requisitos de segurança da informação devem ser identificados, especificados e aprovados ao desenvolver ou adquirir aplicações.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.27",
				"title": "Princípios de arquitetura e engenharia de sistemas seguros",
				"description": "Princípios para engenharia de sistemas seguros devem ser estabelecidos, documentados, mantidos e aplicados a qualquer atividade de desenvolvimento de sistemas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.28",
				"title": "Codificação segura",
				"description": "Princípios de codificação segura devem ser aplicados ao desenvolvimento de software.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.29",
				"title": "Testes de segurança em desenvolvimento e aceitação",
				"description": "Processos de teste de segurança devem ser definidos e implementados no ciclo de vida do desenvolvimento.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.30",
				"title": "Desenvolvimento terceirizado",
				"description": "A organização deve dirigir, monitorar e analisar criticamente as atividades relacionadas à terceirização de desenvolvimento de sistemas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.31",
				"title": "Separação dos ambientes de desenvolvimento, teste e produção",
				"description": "Ambientes de desenvolvimento, testes e produção devem ser separados e protegidos.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.32",
				"title": "Gestão de mudanças",
				"description": "Mudanças nos recursos de tratamento de informações e sistemas de informação devem estar sujeitas a procedimentos de gestão de mudanças.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.33",
				"title": "Informações de teste",
				"description": "Informações de teste devem ser adequadamente selecionadas, protegidas e gerenciadas.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			},
			{
				"code": "8.34",
				"title": "Proteção de sistemas de informação durante os testes de auditoria",
				"description": "Testes de auditoria e outras atividades de garantia envolvendo a avaliação de sistemas operacionais devem ser planejados e acordados entre o testador e a gestão apropriada.",
				"type": "controles tecnológicos",
				"iso_type": Control.ISOType.ISO_27001,
			}
		]
		Control.objects.bulk_create([Control(**control) for control in controls])